[project]
name = "webtrc-demo"
version = "0.1.0"
description = "A WebRTC audio chat demo with FastAPI."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "aiortc",
    "websockets",
]
